view_group:
  model: employee_skill
  primary: employee_skill
  navigation: false
  breadcrumb:
    relation: employee
  views:
    - page: employee_skill
      label: "Employee Skills"
      icon: star
