view_group:
  model: employee
  primary: employee
  navigation: false
  views:
    - page: employee
      label: "Management"
      icon: users
    - page: employee_directory
      label: "Directory"
      icon: book
    - page: employee_archive
      label: "Archive"
      icon: archive
