view_group:
  model: leave_request
  primary: leave_request
  navigation: false
  breadcrumb:
    relation: employee
  views:
    - presenter: leave_request
      label: "Leave Requests"
      icon: calendar-plus
