menu:
  top_menu:
    - label: "Features"
      icon: star
      children:
        - view_group: showcase_fields
        - view_group: showcase_models
        - view_group: showcase_forms
        - separator: true
        - view_group: showcase_attachments
        - view_group: showcase_permissions
        - view_group: permission_configs
        - view_group: roles
        - view_group: showcase_extensibility
        - view_group: showcase_virtual_fields
        - view_group: showcase_recipes
        - separator: true
        - view_group: showcase_searches
        - view_group: saved_filters
        - view_group: showcase_positioning
        - view_group: showcase_userstamps
        - view_group: showcase_soft_delete

    - label: "Blog"
      icon: file-text
      children:
        - view_group: articles
        - view_group: categories
        - separator: true
        - view_group: authors
        - view_group: tags

    - label: "Organization"
      icon: building
      children:
        - view_group: departments
        - view_group: employees
        - view_group: projects
        - separator: true
        - view_group: groups
        - view_group: group_memberships
        - view_group: group_role_mappings

    - label: "Pipelines"
      icon: git-branch
      children:
        - view_group: pipelines
        - view_group: pipeline_stages

    - view_group: features
