view_group:
  model: article
  primary: articles
  breadcrumb:
    relation: category
  views:
    - presenter: articles
      label: "Table"
      icon: file-text
    - presenter: articles_tiles
      label: "Tiles"
      icon: grid-2x2
