view_group:
  model: employee
  primary: employees
  breadcrumb:
    relation: department
  views:
    - presenter: employees
      label: "Table"
      icon: users
    - presenter: employees_tiles
      label: "Tiles"
      icon: grid-2x2
