view_group:
  model: feature
  primary: features_card
  views:
    - page: features_card
      label: "Card View"
      icon: layout
    - page: features_table
      label: "Table View"
      icon: grid
    - page: features_tiles
      label: "Tiles"
      icon: grid-2x2
