view_group:
  model: showcase_field
  primary: showcase_fields_table
  views:
    - page: showcase_fields_table
      label: "Table View"
      icon: grid
    - page: showcase_fields_card
      label: "Card View"
      icon: layout
    - page: showcase_fields_tiles
      label: "Tiles"
      icon: grid-2x2
