view_group:
  model: company
  primary: company
  navigation: false
  views:
    - page: company
      label: "Detailed"
      icon: maximize
    - page: company_short
      label: "Short"
      icon: list
    - page: company_tiles
      label: "Tiles"
      icon: grid
    - page: company_archive
      label: "Archived"
      icon: archive
