view_group:
  model: contact
  primary: contact
  navigation: false
  breadcrumb:
    relation: company
  views:
    - page: contact
      label: "Detailed"
      icon: maximize
    - page: contact_short
      label: "Short"
      icon: list
    - page: contact_tiles
      label: "Tiles"
      icon: grid
